name: counting
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=4.9.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - async-lru=2.0.5
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cached-property=1.5.2
  - cached_property=1.5.2
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - fqdn=1.5.1
  - h11=0.14.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.1.0
  - importlib-metadata=8.6.1
  - isoduration=20.11.0
  - jedi=0.19.2
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=7.4.9
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - mistune=2.0.5
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - ncurses=6.4
  - notebook=7.4.0
  - notebook-shim=0.2.4
  - openssl=3.0.16
  - overrides=7.7.0
  - pandocfilters=1.5.0
  - pip=25.0
  - prometheus_client=0.21.1
  - python=3.11.11
  - python-json-logger=2.0.7
  - python_abi=3.11
  - pyzmq=24.0.1
  - readline=8.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - send2trash=1.8.3
  - setuptools=75.8.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.45.3
  - terminado=0.18.1
  - tk=8.6.14
  - tomli=2.2.1
  - types-python-dateutil=2.9.0.20241206
  - typing_extensions=4.13.2
  - typing_utils=0.1.0
  - uri-template=1.3.0
  - webcolors=24.11.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
      - accelerate==1.5.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - alembic==1.16.1
      - annotated-types==0.7.0
      - asttokens==3.0.0
      - attrs==25.3.0
      - av==14.2.0
      - bitsandbytes==0.45.3
      - blis==1.2.0
      - cairocffi==1.7.1
      - cairosvg==2.7.1
      - captum==0.8.0
      - catalogue==2.0.10
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpathlib==0.21.0
      - colorlog==6.9.0
      - comm==0.2.2
      - confection==0.1.5
      - contourpy==1.3.1
      - cssselect2==0.8.0
      - cycler==0.12.1
      - cymem==2.0.11
      - cython==3.0.12
      - datasets==3.3.2
      - debugpy==1.8.13
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - evaluate==0.4.3
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.17.0
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - greenlet==3.2.2
      - hf-xet==1.1.5
      - huggingface-hub==0.33.0
      - idna==3.10
      - imageio==2.37.0
      - ipykernel==6.29.5
      - ipython==9.0.2
      - ipython-pygments-lexers==1.1.1
      - jinja2==3.1.6
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - kaleido==0.2.1
      - kiwisolver==1.4.8
      - langcodes==3.5.0
      - language-data==1.3.0
      - lazy-loader==0.4
      - mako==1.3.10
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - murmurhash==1.0.12
      - narwhals==1.33.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - open-clip-torch==2.31.0
      - optuna==4.3.0
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - peft==0.14.0
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.6
      - plotly==6.0.1
      - preshed==3.0.9
      - prompt-toolkit==3.0.50
      - propcache==0.3.0
      - protobuf==6.30.0
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==19.0.1
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - qwen-vl-utils==0.0.10
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - rpds-py==0.24.0
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sentry-sdk==2.29.1
      - setproctitle==1.3.6
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.1.0
      - smmap==5.0.2
      - spacy==3.8.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.41
      - srsly==2.5.1
      - stack-data==0.6.3
      - sympy==1.13.1
      - thinc==8.3.4
      - threadpoolctl==3.6.0
      - tifffile==2025.2.18
      - timm==1.0.15
      - tinycss2==1.4.0
      - tokenizers==0.21.1
      - torch==2.6.0
      - torchvision==0.21.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.52.4
      - triton==3.2.0
      - typer==0.15.2
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - wandb==0.19.11
      - wasabi==1.1.3
      - wcwidth==0.2.13
      - weasel==0.4.1
      - webencodings==0.5.1
      - wrapt==1.17.2
      - xxhash==3.5.0
      - yarl==1.18.3
